version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: meu-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: mei_i_help_you
      MYSQL_USER: root
      MYSQL_PASSWORD:
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
